---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: This command will change the working directory to somedir/
      ansible.builtin.shell:
        cmd: ls -l | grep log
        chdir: somedir/
