---
- hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        sleep: 60
        timeout: 300
      vars:
        ansible_user: ec2-user

- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Copy file script
      ansible.builtin.copy:
        src: ./cloudinit.sh
        dest: /usr/bin/cloudinit.sh
        mode: '0744'
        directory_mode: '0755'
    - name: Execute file script
      ansible.builtin.command:
        cmd: /usr/bin/cloudinit.sh
    - name: Start docker
      ansible.builtin.service:
        name: docker
        state: started
    - name: Enable docker
      ansible.builtin.service:
        name: docker
        enabled: yes

- hosts: all
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Execute file script
      ansible.builtin.shell:
        cmd: docker-compose pull && docker-compose up -d
