---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Up docker
      ansible.builtin.shell:
        cmd: /usr/local/bin/docker-compose pull && /usr/local/bin/docker-compose docker-compose up -d
