---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Up docker
      ansible.builtin.shell:
        cmd: /bin/bash docker-compose pull && /bin/bash docker-compose up -d
